// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	  int N =  Integer.parseInt(args[0]);
	  double countS = 0, countB = 0 ;
	  for(int i=0 ; i < N ; i++)
	  {
      double r = Math.random() ;
	  if(r > 0.5)
	  {
		countB ++ ;
	  }
	  else
	  {
		countS ++ ;
	  }
	  }
	  
	  System.out.println("> 0.5:  " + countB + " times");
	  System.out.println("<= 0.5: " + countS + " times");
	 if( (countB != 0) && (countS != 0))
	  {
		double ratio = countB / countS ;
	  System.out.println("Ratio   " + ratio );
	}
}
}
